
//categories
export const GET_COLLECTIONS_CONFIG = "GET_COLLECTIONS_CONFIG";
export const GET_COLLECTIONS_CONFIG_SUCCESS = "GET_COLLECTIONS_CONFIG_SUCCESS";
export const ADD_COLLECTIONS_CONFIG = "ADD_COLLECTIONS_CONFIG";
export const ADD_COLLECTIONS_CONFIG_SUCCESS = "ADD_COLLECTIONS_CONFIG_SUCCESS";
export const UPDATE_COLLECTIONS_CONFIG = "UPDATE_COLLECTIONS_CONFIG";
export const UPDATE_COLLECTIONS_CONFIG_SUCCESS = "UPDATE_COLLECTIONS_CONFIG_SUCCESS";

// items
export const GET_ITEMS_CONFIG = "GET_ITEMS_CONFIG";
export const GET_ITEMS_CONFIG_SUCCESS = "GET_ITEMS_CONFIG_SUCCESS";
export const ADD_ITEMS_CONFIG = "ADD_ITEMS_CONFIG";
export const ADD_ITEMS_CONFIG_SUCCESS = "ADD_ITEMS_CONFIG_SUCCESS";