export const GET_ALL_CREDIT = "GET_ALL_CREDIT";
export const GET_ALL_CREDIT_SUCCESS = "GET_ALL_CREDIT_SUCCESS";

export const ADD_NEW_CREDIT = "ADD_NEW_CREDIT";
export const ADD_NEW_CREDIT_SUCCESS = "ADD_NEW_CREDIT_SUCCESS";

export const UPDATE_CREDIT = "UPDATE_CREDIT";
export const UPDATE_CREDIT_SUCCESS = "UPDATE_CREDIT_SUCCESS";


export const GET_CREDIT_BY_ID = "GET_CREDIT_BY_ID";
export const GET_CREDIT_BY_ID_SUCCESS = "GET_CREDIT_BY_ID_SUCCESS";



export const DELETE_CREDIT = "DELETE_CREDIT";
export const DELETE_CREDIT_SUCCESS = "DELETE_CREDIT_SUCCESS";
