export const GET_ALL_CORPORATE_ADMIN = "GET_ALL_CORPORATE_ADMIN";
export const GET_ALL_CORPORATE_ADMIN_SUCCESS = "GET_ALL_CORPORATE_ADMIN_SUCCESS";

export const ADD_NEW_CORPORATE_ADMIN = "ADD_NEW_CORPORATE_ADMIN";
export const ADD_NEW_CORPORATE_ADMIN_SUCCESS = "ADD_NEW_CORPORATE_ADMIN_SUCCESS";

export const UPDATE_CORPORATE_ADMIN = "UPDATE_CORPORATE_ADMIN";
export const UPDATE_CORPORATE_ADMIN_SUCCESS = "UPDATE_CORPORATE_ADMIN_SUCCESS";
export const DELETE_CORPORATE_ADMIN = "DELETE_CORPORATE_ADMIN";
export const DELETE_CORPORATE_ADMIN_SUCCESS = "DELETE_CORPORATE_ADMIN_SUCCESS";
