export const GET_OPTION_CONFIG = "GET_OPTION_CONFIG";
export const GET_OPTION_CONFIG_SUCCESS = "GET_OPTION_CONFIG_SUCCESS";
export const ADD_OPTION_CONFIG = "ADD_OPTION_CONFIG";
export const ADD_OPTION_CONFIG_SUCCESS = "ADD_OPTION_CONFIG_SUCCESS";
export const UPDATE_OPTION_CONFIG = "UPDATE_OPTION_CONFIG";
export const UPDATE_OPTION_CONFIG_SUCCESS = "UPDATE_OPTION_CONFIG_SUCCESS";
export const DELETE_OPTION = "DELETE_OPTION";
export const DELETE_OPTION_SUCCESS = "DELETE_OPTION_SUCCESS";
