export const GET_CORPORATE_CONFIG = "GET_CORPORATE_CONFIG";
export const GET_CORPORATE_CONFIG_SUCCESS =
  "GET_CORPORATE_CONFIG_SUCCESS";
export const UPDATE_CORPORATE_CONFIG = "UPDATE_CORPORATE_CONFIG";
export const UPDATE_CORPORATE_CONFIG_SUCCESS =
  "UPDATE_CORPORATE_CONFIG_SUCCESS";
