// export const GET_ALL_TEAMS = "GET_ALL_TEAMS";
// export const GET_ALL_TEAMS_SUCCESS = "GET_ALL_TEAMS_SUCCESS";

// export const ADD_NEW_TEAM = "ADD_NEW_TEAM";
// export const ADD_NEW_TEAM_SUCCESS = "ADD_NEW_MEMEBER_SUCCESS";

// export const UPDATE_TEAM = "UPDATE_TEAM";
// export const UPDATE_TEAM_SUCCESS = "UPDATE_TEAM_SUCCESS";

// export const DELETE_TEAM = "DELETE_TEAM";
// export const DELETE_TEAM_SUCCESS = "DELETE_TEAM_SUCCESS";
