export const GET_CONDITION_CONFIG = "GET_CONDITION_CONFIG";
export const GET_CONDITION_CONFIG_SUCCESS = "GET_CONDITION_CONFIG_SUCCESS";
export const ADD_CONDITION_CONFIG = "ADD_CONDITION_CONFIG";
export const ADD_CONDITION_CONFIG_SUCCESS = "ADD_CONDITION_CONFIG_SUCCESS";
export const UPDATE_CONDITION_CONFIG = "UPDATE_CONDITION_CONFIG";
export const UPDATE_CONDITION_CONFIG_SUCCESS = "UPDATE_CONDITION_CONFIG_SUCCESS";
export const DELETE_CONDITION = "DELETE_CONDITION";
export const DELETE_CONDITION_SUCCESS = "DELETE_CONDITION_SUCCESS";
