export const FORMS_LIST_LOADING =
  "forms/FORMS_LIST_LOADING";
export const FORMS_LIST_SUCCESS =
  "forms/FORMS_LIST_SUCCESS";
export const FORMS_RESET = "forms/FORMS_LIST_RESET";
export const FORMS_API_ERROR = "forms/API_ERROR";
export const RETRIEVE_FORM = "forms/RETRIEVE_FORM";
export const RETRIEVE_FORM_SUCCESS =
  "forms/RETRIEVE_FORM_SUCCESS";
export const ADD_FORM_INFORMATION = "ADD_FORM_INFORMATION";
export const ADD_FORM_INFORMATION_SUCCESS =
  "ADD_FORM_INFORMATION_SUCCESS";
export const ADD_FORM_DATA = "ADD_FORM_DATA";
export const ADD_FORM_DATA_SUCCESS =
  "ADD_FORM_DATA_SUCCESS";
export const ADD_NEW_FORM_ADMIN = "ADD_FORM_ADMIN";
export const ADD_NEW_FORM_ADMIN_SUCCESS =
  "ADD_FORM_ADMIN_SUCCESS";
export const SFTP_CONNECTION = "SFTP_CONNECTION";
export const SFTP_CONNECTION_SUCCESS = "SFTP_CONNECTION_SUCCESS";

export const ENABLE_EDIT_MODE = "ENABLE_EDIT_MODE";
export const DISABLE_EDIT_MODE = "DISABLE_EDIT_MODE";
export const NEXT_STEP = "NEXT_STEP";

export const EDIT_FORM_INFORMATION = "EDIT_FORM_INFORMATION";
export const EDIT_FORM_INFORMATION_SUCCESS =
  "EDIT_FORM_INFORMATION_SUCCESS";
export const EDIT_FORM_DATA = "EDIT_FORM_DATA";
export const EDIT_FORM_DATA_SUCCESS =
  "EDIT_FORM_DATA_SUCCESS";
export const TOGGLE_FORM = "TOGGLE_FORM";
export const TOGGLE_FORM_SUCCESS = "TOGGLE_FORM_SUCCESS";
