export const GET_PROFILE_DETAILES = "GET_PROFILE_DETAILES";
export const GET_PROFILE_DETAILES_SUCCESS = "GET_PROFILE_DETAILES_SUCCESS";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
